### PR TITLE
Upgrading bash completion script to latest version

### PR DESCRIPTION
**Pull request by 9still**
Upgrading with latest versions from https://github.com/git/git/tree/master/contrib/completion

Would be good to test it first to make sure it works for you as well :)

### CODE REVIEW

**Comment by Prestaul** [comment]
@nbroslawsky I've pulled this down and I'm testing it. If it looks good after a couple days of work I may merge it early next week if you haven't already.

@gmatroskin, thanks for the PR!

**Comment by nbroslawsky** [comment]
Sure, let me know. I haven't merged it yet because I haven't been able to test it.

**Comment by Prestaul** [comment]
@gmatroskin the `git-prompt.sh` file appears to only contain html... Any chance you could add the correct file?

https://github.com/gmatroskin/githelpers/blob/6a9b1e118389657bbb700279e068f4b88a63d14b/git-prompt.sh

**Comment by 9still** [comment]
Whoops, sorry about that @Prestaul.  I refetched `git-prompt.sh` from the git repo right before I created the PR & must've borked the URL.   Updated.

**Comment by Prestaul** [comment]
@gmatroskin no problem. I've been using it for a while and it looks like it is working perfectly for me. Thanks for the fix. :)

@nbroslawsky you can probably merge this safely if you'd like, otherwise I'll keep using it for a couple days and if I don't see any issues I'll merge at the end of the week.

**Comment by nbroslawsky** [comment]
Done and done!

**Pull request merged**
